In [4]:
import numpy as np
np.random.seed(42)
import warnings
warnings.filterwarnings('ignore')

In [5]:
def MSE(x_batch, y_batch, lr, w, b):
    y_pred = np.matmul(x_batch,w) + b
    error = y_batch - y_pred

    w_new = w + lr * np.matmul(error,x_batch)
    b_new = b + lr * error.sum()
    return w_new,b_new

def MiniBatchGD(x,y,batch_size = 20,epochs = 25, lr = 0.005):
    n_values = x.shape[0]
    w = np.zeros(x.shape[1])
    b = 0

    regression_coef = []
    for _ in range(epochs):
        batch = np.random.choice(range(n_values),batch_size)
        x_batch = x[batch,:]
        y_batch = y[batch]
        w,b = MSE(x_batch,y_batch,lr,w,b)

        regression_coef.append(np.hstack((w,b)))

    return regression_coef

data = np.loadtxt("datasets/data.csv",delimiter=',')
x = data[:,:-1]
y = data[:,-1]
regression_coef = np.array(MiniBatchGD(x,y))

In [6]:
print(regression_coef.shape)

(25, 2)

SKlearn

In [7]:
from sklearn.linear_model import LinearRegression
import pandas as pd
model = LinearRegression()

In [8]:
data = pd.read_csv('datasets/bmi.csv')
data

                Country  Life expectancy       BMI
0           Afghanistan             52.8  20.62058
1               Albania             76.8  26.44657
2               Algeria             75.5  24.59620
3               Andorra             84.6  27.63048
4                Angola             56.7  22.25083
..                  ...              ...       ...
158             Vanuatu             63.4  26.78926
159  West Bank and Gaza             74.1  26.57750
160             Vietnam             74.1  20.91630
161              Zambia             51.1  20.68321
162            Zimbabwe             47.3  22.02660

[163 rows x 3 columns]

In [9]:
model.fit(data[["BMI"]],data[["Life expectancy"]])

LinearRegression()

In [10]:
print(model.predict([[20.62058]]))

[[59.16034509]]

Boston dataset

In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [12]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :],  raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]
df = pd.DataFrame(data)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [13]:
x_train,x_test,y_train,y_test =  train_test_split(df[[0,1,2,3,4,5,6,7,8,9,10,11]],df[[12]],random_state=42,test_size=0.2)

In [14]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [15]:
x_test

,0,1,2,3,4,5,6,7,8,9,10,11
173,0.09178,0.0,4.05,0.0,0.510,6.416,84.1,2.6463,5.0,296.0,16.6,395.50
274,0.05644,40.0,6.41,1.0,0.447,6.758,32.9,4.0776,4.0,254.0,17.6,396.90
491,0.10574,0.0,27.74,0.0,0.609,5.983,98.8,1.8681,4.0,711.0,20.1,390.11
72,0.09164,0.0,10.81,0.0,0.413,6.065,7.8,5.2873,4.0,305.0,19.2,390.91
452,5.09017,0.0,18.10,0.0,0.713,6.297,91.8,2.3682,24.0,666.0,20.2,385.09
...,...,...,...,...,...,...,...,...,...,...,...,...
412,18.81100,0.0,18.10,0.0,0.597,4.628,100.0,1.5539,24.0,666.0,20.2,28.79
436,14.42080,0.0,18.10,0.0,0.740,6.461,93.3,2.0026,24.0,666.0,20.2,27.49
411,14.05070,0.0,18.10,0.0,0.597,6.657,100.0,1.5275,24.0,666.0,20.2,35.05
86,0.05188,0.0,4.49,0.0,0.449,6.015,45.1,4.4272,3.0,247.0,18.5,395.99
75,0.09512,0.0,12.83,0.0,0.437,6.286,45.0,4.5026,5.0,398.0,18.7,383.23

In [16]:
x_test[0:-1]

,0,1,2,3,4,5,6,7,8,9,10,11
173,0.09178,0.0,4.05,0.0,0.510,6.416,84.1,2.6463,5.0,296.0,16.6,395.50
274,0.05644,40.0,6.41,1.0,0.447,6.758,32.9,4.0776,4.0,254.0,17.6,396.90
491,0.10574,0.0,27.74,0.0,0.609,5.983,98.8,1.8681,4.0,711.0,20.1,390.11
72,0.09164,0.0,10.81,0.0,0.413,6.065,7.8,5.2873,4.0,305.0,19.2,390.91
452,5.09017,0.0,18.10,0.0,0.713,6.297,91.8,2.3682,24.0,666.0,20.2,385.09
...,...,...,...,...,...,...,...,...,...,...,...,...
371,9.23230,0.0,18.10,0.0,0.631,6.216,100.0,1.1691,24.0,666.0,20.2,366.15
412,18.81100,0.0,18.10,0.0,0.597,4.628,100.0,1.5539,24.0,666.0,20.2,28.79
436,14.42080,0.0,18.10,0.0,0.740,6.461,93.3,2.0026,24.0,666.0,20.2,27.49
411,14.05070,0.0,18.10,0.0,0.597,6.657,100.0,1.5275,24.0,666.0,20.2,35.05
86,0.05188,0.0,4.49,0.0,0.449,6.015,45.1,4.4272,3.0,247.0,18.5,395.99

In [17]:
y_pred = model.predict(x_test)
y_pred

array([[11.21388683],
       [ 4.62819968],
       [16.4560021 ],
       [ 6.98750286],
       [16.93139801],
       [11.43040623],
       [14.44235333],
       [15.62590395],
       [15.44391253],
       [13.94046723],
       [13.43497568],
       [14.0386136 ],
       [29.66943107],
       [10.01910071],
       [14.37004626],
       [11.17175325],
       [17.11596028],
       [24.31238551],
       [ 1.12125759],
       [18.13464824],
       [ 7.31744332],
       [ 7.51193168],
       [16.64467247],
       [10.75366615],
       [19.04849454],
       [20.30915272],
       [10.16250283],
       [18.01395403],
       [12.81794672],
       [14.30492687],
       [15.29317045],
       [ 9.40259372],
       [13.21653283],
       [21.86079508],
       [17.61463776],
       [20.32211255],
       [ 6.11812951],
       [11.71796682],
       [ 9.89301842],
       [ 6.16186389],
       [16.27044965],
       [ 8.98559786],
       [ 0.88712842],
       [11.15027007],
       [ 9.60068103],
       [19.82109403],
       [16.73652148],
       [ 5.37896728],
       [15.63343877],
       [ 9.10287483],
       [13.67613679],
       [ 5.0117657 ],
       [14.28835509],
       [ 9.47487883],
       [ 4.67669946],
       [12.61745788],
       [18.0916926 ],
       [ 6.17590279],
       [ 8.39016186],
       [14.58165519],
       [ 7.77688585],
       [ 4.11261494],
       [ 6.35914534],
       [13.7144547 ],
       [ 7.66801995],
       [16.16052025],
       [16.63639963],
       [ 7.98858899],
       [ 6.59862308],
       [20.55789019],
       [10.07041248],
       [12.03617405],
       [20.90899189],
       [10.30516536],
       [ 9.72151957],
       [22.98988762],
       [13.63980408],
       [ 1.77814354],
       [16.51293848],
       [19.24598766],
       [ 9.56129995],
       [19.90077556],
       [ 9.19626615],
       [23.07509404],
       [14.36877117],
       [ 7.58146384],
       [15.87261996],
       [ 8.52705586],
       [ 9.03213833],
       [14.7434111 ],
       [10.19267736],
       [23.74369497],
       [15.32908737],
       [11.18758727],
       [28.91938998],
       [15.18396044],
       [17.45177461],
       [27.07222669],
       [19.49266548],
       [17.73095989],
       [ 9.79709873],
       [ 9.07548127]])

In [18]:
y_test = np.array(y_test)

In [20]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [21]:
print("Mean square error",np.sqrt(mean_squared_error(y_pred,y_test)))
print("r2_score",r2_score(y_pred,y_test))

Mean square error 3.98466047259547
r2_score 0.5313507990238133